version: '3'

services:
  flask:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"

  nginx:
    volumes:
      - ssl-certs:/etc/nginx/certs
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask

volumes:
  ssl-certs:
    external: true