version: '3'

services:
  flask:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"

  nginx:
    volumes:
      - ssl-certs:/etc/nginx/certs
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8000:80"
      - "8443:443" # Expose port 443 for HTTPS traffic
    depends_on:
      - flask

volumes:
  ssl-certs:
